[sidebar]
emoji = ""
subtitle = "Software Engineer"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"